spring.application.name=ms-vedas
server.port=8087
spring.datasource.url=jdbc:postgresql://ep-royal-credit-apd69c3y.c-7.us-east-1.aws.neon.tech/auth_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_McRpr6N8YBaT
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
