spring.application.name=ms-vedas
server.port=10000
spring.datasource.url=jdbc:postgresql://ep-royal-credit-apd69c3y.c-7.us-east-1.aws.neon.tech/vedas_db?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_McRpr6N8YBaT
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
app.ms-especies.url=https://ms-especies.onrender.com
